### ISSUE TITLE
Post Feed / Landing Page

### ISSUE THREAD

**Issue by cawleygl** [AnnabellAnastasia/PM_Group_1#16]
Create Front End Post Feed and Landing Page

**Comment by AnnabellAnastasia** [comment]
Given the user has logged into the platform and is on the landing page.
When the user views the post feed.
Then the feed should show recent and relevant posts in an easy-to-read format.

**Comment by cawleygl** [comment]
User Story: As a professor, I want to make public posts so that I can offer career advice to both current and former students.

**Comment by cawleygl** [comment]
<img width="1720" alt="Screenshot 2024-11-15 at 5 37 04 PM" src="https://github.com/user-attachments/assets/55e28306-b70e-496f-bdbd-6f05cc0dac1b">
